all : lineas_1.txt lineas_2.txt 

lineas_1.txt : lineas.py numeros.txt 
	python lineas.py

lineas_2.txt : lineas.py numeros.txt 
	python lineas.py

numeros.x : numeros.c
	gcc numeros.c -o numeros.x

numeros.txt: numeros.x
	./numeros.x > numeros.txt


